manually finetuning SOTA model on single basin

In [2]:
from experiment.utils import TrainedModel, TrainedModelID
import pandas as pd
model = TrainedModel(TrainedModelID.SOTA_20)

In [3]:
df = pd.read_csv(model.metrics_file)

In [4]:
df.head()

,basin,NSE,KGE,Alpha-NSE,Beta-NSE,MSE,RMSE,Pearson-r,Beta-KGE,FHV,FMS,FLV,Peak-Timing,Missed-Peaks,Peak-MAPE
0,1022500,0.857133,0.892788,1.009322,0.074674,0.703404,0.838692,0.932032,1.082388,-1.957188,-5.274799,-848.639937,0.304348,0.400000,22.719163
1,1031500,0.886572,0.871342,1.011726,0.074345,1.065545,1.032252,0.946743,1.116529,2.461385,-11.532134,-425.578941,0.090909,0.300000,18.899822
2,1047000,0.886588,0.916449,0.949255,-0.020842,1.210360,1.100163,0.941848,0.968000,-5.867308,-4.868418,-109.980933,0.136364,0.296296,22.547457
3,1052500,0.858710,0.885014,0.928502,-0.033539,1.850370,1.360283,0.927274,0.946890,-7.766392,-11.314812,33.631946,0.090909,0.457627,25.661473
4,1054200,0.765390,0.754837,0.787890,-0.012829,6.914524,2.629548,0.879771,0.974330,-22.701938,-10.492230,34.604226,0.181818,0.438596,35.046749

In [5]:
basin_data = df.loc[df['NSE'] < df['NSE'].median()].sample(n=1)

In [16]:
basin = basin_data.basin.iloc[0]
basin

2245500

In [9]:
basin_data

,basin,NSE,KGE,Alpha-NSE,Beta-NSE,MSE,RMSE,Pearson-r,Beta-KGE,FHV,FMS,FLV,Peak-Timing,Missed-Peaks,Peak-MAPE
134,2245500,0.573356,0.563418,0.694736,-0.098427,1.805394,1.34365,0.766983,0.792344,-27.191141,-14.650566,8.216134,0.578947,0.571429,62.282281

In [20]:
finetune_path = '/home/admin/Fine-Flood-Forecasts/experiment/models/finetune.yml'
with open(finetune_path, 'a') as fp:
    fp.write(f'\nbase_run_dir: {model.run_dir.absolute()}')

In [21]:
with open('/home/admin/Fine-Flood-Forecasts/experiment/models/finetune_basin.txt', 'w') as fp:
    fp.write(str(basin))

In [29]:
from neuralhydrology.nh_run import finetune
from pathlib import Path
finetune(Path(finetune_path))

2024-09-18 12:40:23,782: Logging to /home/admin/Fine-Flood-Forecasts/experiment/runs/cudalstm_531_basins_finetuned/output.log initialized.
2024-09-18 12:40:23,783: ### Folder structure created at /home/admin/Fine-Flood-Forecasts/experiment/runs/cudalstm_531_basins_finetuned
2024-09-18 12:40:23,783: ### Start finetuning with pretrained model stored in /home/admin/Fine-Flood-Forecasts/experiment/models/runs/sota_20
2024-09-18 12:40:23,784: ### Run configurations for cudalstm_531_basins_finetuned
2024-09-18 12:40:23,784: additional_feature_files: None
2024-09-18 12:40:23,784: batch_size: 256
2024-09-18 12:40:23,785: checkpoint_path: None
2024-09-18 12:40:23,785: clip_gradient_norm: 1
2024-09-18 12:40:23,785: clip_targets_to_zero: ['QObs(mm/d)']
2024-09-18 12:40:23,786: commit_hash: 6dde7b4
2024-09-18 12:40:23,786: data_dir: /home/admin/Fine-Flood-Forecasts/data/CAMELS_US
2024-09-18 12:40:23,786: dataset: camels_us
2024-09-18 12:40:23,787: device: cuda:0
2024-09-18 12:40:23,787: dynamic_inputs: ['PRCP(mm/day)_nldas', 'SRAD(W/m2)_nldas', 'Tmax(C)_nldas', 'Tmin(C)_nldas', 'Vp(Pa)_nldas', 'PRCP(mm/day)_maurer', 'SRAD(W/m2)_maurer', 'Tmax(C)_maurer', 'Tmin(C)_maurer', 'Vp(Pa)_maurer', 'prcp(mm/day)_daymet', 'srad(W/m2)_daymet', 'tmax(C)_daymet', 'tmin(C)_daymet', 'vp(Pa)_daymet']
2024-09-18 12:40:23,787: epochs: 10
2024-09-18 12:40:23,788: evolving_attributes: None
2024-09-18 12:40:23,789: experiment_name: cudalstm_531_basins_finetuned
2024-09-18 12:40:23,789: forcings: ['daymet', 'maurer', 'nldas']
2024-09-18 12:40:23,790: head: regression
2024-09-18 12:40:23,790: hidden_size: 256
2024-09-18 12:40:23,790: img_log_dir: /home/admin/Fine-Flood-Forecasts/experiment/runs/cudalstm_531_basins_finetuned/img_log
2024-09-18 12:40:23,791: initial_forget_bias: 3
2024-09-18 12:40:23,791: learning_rate: {0: 0.0005, 2: 5e-05}
2024-09-18 12:40:23,791: log_interval: 5
2024-09-18 12:40:23,792: log_n_figures: 1
2024-09-18 12:40:23,793: log_tensorboard: True
2024-09-18 12:40:23,793: loss: NSE
2024-09-18 12:40:23,793: metrics: ['NSE', 'KGE', 'Alpha-NSE', 'Beta-NSE', 'MSE', 'RMSE', 'Pearson-r', 'Beta-KGE', 'FHV', 'FMS', 'FLV', 'Peak-Timing', 'Missed-Peaks', 'Peak-MAPE']
2024-09-18 12:40:23,794: model: cudalstm
2024-09-18 12:40:23,794: num_workers: 16
2024-09-18 12:40:23,794: number_of_basins: 1
2024-09-18 12:40:23,795: optimizer: Adam
2024-09-18 12:40:23,795: output_activation: linear
2024-09-18 12:40:23,795: output_dropout: 0.4
2024-09-18 12:40:23,796: package_version: 1.11.0
2024-09-18 12:40:23,796: predict_last_n: 1
2024-09-18 12:40:23,796: regularization: None
2024-09-18 12:40:23,797: run_dir: /home/admin/Fine-Flood-Forecasts/experiment/runs/cudalstm_531_basins_finetuned
2024-09-18 12:40:23,797: save_weights_every: 1
2024-09-18 12:40:23,797: seed: 721924
2024-09-18 12:40:23,798: seq_length: 365
2024-09-18 12:40:23,798: static_attributes: ['elev_mean', 'slope_mean', 'area_gages2', 'frac_forest', 'lai_max', 'lai_diff', 'gvf_max', 'gvf_diff', 'soil_depth_pelletier', 'soil_depth_statsgo', 'soil_porosity', 'soil_conductivity', 'max_water_content', 'sand_frac', 'silt_frac', 'clay_frac', 'carbonate_rocks_frac', 'geol_permeability', 'p_mean', 'pet_mean', 'aridity', 'frac_snow', 'high_prec_freq', 'high_prec_dur', 'low_prec_freq', 'low_prec_dur']
2024-09-18 12:40:23,798: target_noise_std: None
2024-09-18 12:40:23,799: target_variables: ['QObs(mm/d)']
2024-09-18 12:40:23,799: test_basin_file: /home/admin/Fine-Flood-Forecast/experiment/models/finetune_basin.txt
2024-09-18 12:40:23,799: test_end_date: 1999-09-30 00:00:00
2024-09-18 12:40:23,801: test_start_date: 1989-10-01 00:00:00
2024-09-18 12:40:23,801: train_basin_file: /home/admin/Fine-Flood-Forecasts/experiment/models/finetune_basin.txt
2024-09-18 12:40:23,802: train_dir: /home/admin/Fine-Flood-Forecasts/experiment/runs/cudalstm_531_basins_finetuned/train_data
2024-09-18 12:40:23,802: train_end_date: 2008-09-30 00:00:00
2024-09-18 12:40:23,802: train_start_date: 1999-10-01 00:00:00
2024-09-18 12:40:23,803: use_basin_id_encoding: False
2024-09-18 12:40:23,803: validate_every: 3
2024-09-18 12:40:23,803: validate_n_random_basins: 10
2024-09-18 12:40:23,804: validation_basin_file: /home/admin/Fine-Flood-Forecasts/experiment/models/finetune_basin.txt
2024-09-18 12:40:23,804: validation_end_date: 1989-09-30 00:00:00
2024-09-18 12:40:23,804: validation_start_date: 1980-10-01 00:00:00
2024-09-18 12:40:23,805: finetune_modules: ['head']
2024-09-18 12:40:23,805: base_run_dir: /home/admin/Fine-Flood-Forecasts/experiment/models/runs/sota_20
2024-09-18 12:40:23,805: is_finetuning: True
2024-09-18 12:40:23,806: is_continue_training: False
2024-09-18 12:40:23,808: ### Device cuda:0 will be used for training

ValueError: Some basins are missing static attributes.