In [1]:
from experiment.finetuning.main import main
from experiment.utils import TrainedModel, TrainedModelID
from experiment.finetuning.finetune import pick_a_basin, find_best_finetuning_params
from experiment.finetuning.experiments import perform_experiments
from hyperopt import hp

In [2]:
# select base model, start with SOTA Camels model
model = TrainedModel(TrainedModelID.SOTA_20)

lower = 0.0
higher = 0.5

basin, nse = pick_a_basin(model=model, lower=lower, higher=higher)

# define hyperparameter search space
search_space = {
    'basin': basin,
    'epochs': 1 + hp.choice('epochs', [1,2,3,4,5,6,7,8,9,10]),
    'learning_rate': {0: hp.uniform('lr1', 1e-4, 1e-3), 5: hp.uniform('lr2', 1e-5, 1e-4)},
    'lstm': hp.choice('lstm', [True, False]),
    'loss': 'NSE'
}
print(basin)
print(nse)

05591550
0.4111103415489197

In [3]:
# run the finetuning
sweep = find_best_finetuning_params(search_space=search_space, model=model, max_evals=1, evaluate=True)
sweep_results = sweep.save()

2024-09-25 14:28:08,891: Logging to /home/admin/Fine-Flood-Forecasts/experiment/finetuning/runs/basin_05591550/output.log initialized.

2024-09-25 14:28:08,893: ### Folder structure created at /home/admin/Fine-Flood-Forecasts/experiment/finetuning/runs/basin_05591550

2024-09-25 14:28:08,897: ### Start finetuning with pretrained model stored in /home/admin/Fine-Flood-Forecasts/experiment/models/runs/sota_20

2024-09-25 14:28:08,899: ### Run configurations for basin_05591550

2024-09-25 14:28:08,901: additional_feature_files: None

2024-09-25 14:28:08,903: batch_size: 256

2024-09-25 14:28:08,905: checkpoint_path: None

2024-09-25 14:28:08,907: clip_gradient_norm: 1

2024-09-25 14:28:08,909: clip_targets_to_zero: ['QObs(mm/d)']

2024-09-25 14:28:08,911: commit_hash: 6dde7b4

2024-09-25 14:28:08,912: data_dir: /home/admin/Fine-Flood-Forecasts/data/CAMELS_US

2024-09-25 14:28:08,914: dataset: camels_us

2024-09-25 14:28:08,916: device: cuda:0

2024-09-25 14:28:08,918: dynamic_inputs: ['PRCP(mm/day)_nldas', 'SRAD(W/m2)_nldas', 'Tmax(C)_nldas', 'Tmin(C)_nldas', 'Vp(Pa)_nldas', 'PRCP(mm/day)_maurer', 'SRAD(W/m2)_maurer', 'Tmax(C)_maurer', 'Tmin(C)_maurer', 'Vp(Pa)_maurer', 'prcp(mm/day)_daymet', 'srad(W/m2)_daymet', 'tmax(C)_daymet', 'tmin(C)_daymet', 'vp(Pa)_daymet']

2024-09-25 14:28:08,920: epochs: 5

2024-09-25 14:28:08,922: evolving_attributes: None

2024-09-25 14:28:08,924: experiment_name: basin_05591550

2024-09-25 14:28:08,926: forcings: ['daymet', 'maurer', 'nldas']

2024-09-25 14:28:08,928: head: regression

2024-09-25 14:28:08,930: hidden_size: 256

2024-09-25 14:28:08,932: img_log_dir: /home/admin/Fine-Flood-Forecasts/experiment/finetuning/runs/basin_05591550/img_log

2024-09-25 14:28:08,935: initial_forget_bias: 3

2024-09-25 14:28:08,937: learning_rate: {0: 0.000266803032616937, 5: 8.905752446131281e-05}

2024-09-25 14:28:08,939: log_interval: 5

2024-09-25 14:28:08,941: log_n_figures: 1

2024-09-25 14:28:08,943: log_tensorboard: True

2024-09-25 14:28:08,945: loss: NSE

2024-09-25 14:28:08,947: metrics: ['NSE', 'KGE', 'MSE']

2024-09-25 14:28:08,949: model: cudalstm

2024-09-25 14:28:08,950: num_workers: 16

2024-09-25 14:28:08,952: number_of_basins: 1

2024-09-25 14:28:08,954: optimizer: Adam

2024-09-25 14:28:08,956: output_activation: linear

2024-09-25 14:28:08,958: output_dropout: 0.4

2024-09-25 14:28:08,960: package_version: 1.11.0

2024-09-25 14:28:08,962: predict_last_n: 1

2024-09-25 14:28:08,964: regularization: None

2024-09-25 14:28:08,966: run_dir: /home/admin/Fine-Flood-Forecasts/experiment/finetuning/runs/basin_05591550

2024-09-25 14:28:08,968: save_weights_every: 1

2024-09-25 14:28:08,969: seed: 721924

2024-09-25 14:28:08,971: seq_length: 365

2024-09-25 14:28:08,973: static_attributes: ['elev_mean', 'slope_mean', 'area_gages2', 'frac_forest', 'lai_max', 'lai_diff', 'gvf_max', 'gvf_diff', 'soil_depth_pelletier', 'soil_depth_statsgo', 'soil_porosity', 'soil_conductivity', 'max_water_content', 'sand_frac', 'silt_frac', 'clay_frac', 'carbonate_rocks_frac', 'geol_permeability', 'p_mean', 'pet_mean', 'aridity', 'frac_snow', 'high_prec_freq', 'high_prec_dur', 'low_prec_freq', 'low_prec_dur']

2024-09-25 14:28:08,975: target_noise_std: None

2024-09-25 14:28:08,977: target_variables: ['QObs(mm/d)']

2024-09-25 14:28:08,979: test_basin_file: /home/admin/Fine-Flood-Forecasts/experiment/finetuning/assets/finetune_basin.txt

2024-09-25 14:28:08,980: test_end_date: 1999-09-30 00:00:00

2024-09-25 14:28:08,982: test_start_date: 1989-10-01 00:00:00

2024-09-25 14:28:08,984: train_basin_file: /home/admin/Fine-Flood-Forecasts/experiment/finetuning/assets/finetune_basin.txt

2024-09-25 14:28:08,986: train_dir: /home/admin/Fine-Flood-Forecasts/experiment/finetuning/runs/basin_05591550/train_data

2024-09-25 14:28:08,988: train_end_date: 2008-09-30 00:00:00

2024-09-25 14:28:08,989: train_start_date: 1999-10-01 00:00:00

2024-09-25 14:28:08,991: use_basin_id_encoding: False

2024-09-25 14:28:08,993: validate_every: 3

2024-09-25 14:28:08,995: validate_n_random_basins: 531

2024-09-25 14:28:08,997: validation_basin_file: /home/admin/Fine-Flood-Forecasts/experiment/finetuning/assets/finetune_basin.txt

2024-09-25 14:28:08,999: validation_end_date: 1989-09-30 00:00:00

2024-09-25 14:28:09,000: validation_start_date: 1980-10-01 00:00:00

2024-09-25 14:28:09,002: base_run_dir: /home/admin/Fine-Flood-Forecasts/experiment/models/runs/sota_20

2024-09-25 14:28:09,004: finetune_modules: ['head', 'lstm']

2024-09-25 14:28:09,006: is_finetuning: True

2024-09-25 14:28:09,008: is_continue_training: False

2024-09-25 14:28:09,054: ### Device cuda:0 will be used for training

2024-09-25 14:28:09,137: Loading basin data into xarray data set.

  0%|          | 0/1 [00:00<?, ?it/s]
100%|##########| 1/1 [00:00<00:00,  7.38it/s]
100%|##########| 1/1 [00:00<00:00,  7.13it/s]
2024-09-25 14:28:09,293: Calculating target variable stds per basin

  0%|          | 0/1 [00:00<?, ?it/s]
100%|##########| 1/1 [00:00<00:00, 250.65it/s]
2024-09-25 14:28:09,311: Create lookup table and convert to pytorch tensor

  0%|          | 0/1 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?trial/s, best loss=?]

100%|##########| 1/1 [00:02<00:00,  2.17s/it]
100%|##########| 1/1 [00:02<00:00,  2.18s/it]
2024-09-25 14:28:11,832: Starting training from checkpoint /home/admin/Fine-Flood-Forecasts/experiment/models/runs/sota_20/model_epoch030.pt

  0%|          | 0/13 [00:00<?, ?it/s]
# Epoch 1:   0%|          | 0/13 [00:00<?, ?it/s]
# Epoch 1:   0%|          | 0/13 [00:43<?, ?it/s]
  0%|          | 0/1 [00:47<?, ?trial/s, best loss=?]

KeyboardInterrupt:

In [12]:
# now do the experiments
# first, compare performance
sweep_results = f'results/sota_20_{basin}.pkl'
perform_experiments(sweep_results=sweep_results)