In [18]:
# Imports
from pathlib import Path
from experiment.utils import TrainedModel, TrainedModelID, get_losses

import pandas as pd
import torch
from neuralhydrology.nh_run import start_run, eval_run, finetune
from experiment.eval import evaluate_models
import os
import yaml
import matplotlib.pyplot as plt

In [19]:
model = TrainedModel(TrainedModelID.SOTA_20)

df = pd.read_csv(model.metrics_file, dtype={'basin':str})
cutoff = 0.4
basin_data = df.loc[df['NSE'] < cutoff].sample(n=1)
basin = basin_data.basin.iloc[0]
nse = basin_data.NSE.iloc[0]
basin

'09484600'

In [55]:
# Add the path to the pre-trained model to the finetune config
file_path = "finetune.yml"

with open(file_path, "a") as fp:
    fp.write(f"\nbase_run_dir: {model.run_dir.absolute()}")

# Load the existing YAML data
with open(file_path, 'r') as f:
    data = yaml.safe_load(f)

data['experiment_name'] = f'basin_{basin}'  # Example modification

# Write back to the YAML file
with open(file_path, 'w') as f:
    yaml.dump(data, f)

In [56]:
# Create a basin file with the basin we selected above
with open("finetune_basin.txt", "w") as fp:
    fp.write(basin)

In [57]:
# finetune
finetune(Path("finetune.yml"))

2024-09-18 21:10:45,069: Logging to /home/admin/Fine-Flood-Forecasts/experiment/finetuning_playground/runs/basin_09484600/output.log initialized.
2024-09-18 21:10:45,070: ### Folder structure created at /home/admin/Fine-Flood-Forecasts/experiment/finetuning_playground/runs/basin_09484600
2024-09-18 21:10:45,070: ### Start finetuning with pretrained model stored in /home/admin/Fine-Flood-Forecasts/experiment/models/runs/sota_20
2024-09-18 21:10:45,071: ### Run configurations for basin_09484600
2024-09-18 21:10:45,071: additional_feature_files: None
2024-09-18 21:10:45,072: batch_size: 256
2024-09-18 21:10:45,072: checkpoint_path: None
2024-09-18 21:10:45,072: clip_gradient_norm: 1
2024-09-18 21:10:45,073: clip_targets_to_zero: ['QObs(mm/d)']
2024-09-18 21:10:45,073: commit_hash: 6dde7b4
2024-09-18 21:10:45,074: data_dir: /home/admin/Fine-Flood-Forecasts/data/CAMELS_US
2024-09-18 21:10:45,074: dataset: camels_us
2024-09-18 21:10:45,074: device: cuda:0
2024-09-18 21:10:45,075: dynamic_inputs: ['PRCP(mm/day)_nldas', 'SRAD(W/m2)_nldas', 'Tmax(C)_nldas', 'Tmin(C)_nldas', 'Vp(Pa)_nldas', 'PRCP(mm/day)_maurer', 'SRAD(W/m2)_maurer', 'Tmax(C)_maurer', 'Tmin(C)_maurer', 'Vp(Pa)_maurer', 'prcp(mm/day)_daymet', 'srad(W/m2)_daymet', 'tmax(C)_daymet', 'tmin(C)_daymet', 'vp(Pa)_daymet']
2024-09-18 21:10:45,075: epochs: 10
2024-09-18 21:10:45,076: evolving_attributes: None
2024-09-18 21:10:45,076: experiment_name: basin_09484600
2024-09-18 21:10:45,077: forcings: ['daymet', 'maurer', 'nldas']
2024-09-18 21:10:45,077: head: regression
2024-09-18 21:10:45,078: hidden_size: 256
2024-09-18 21:10:45,078: img_log_dir: /home/admin/Fine-Flood-Forecasts/experiment/finetuning_playground/runs/basin_09484600/img_log
2024-09-18 21:10:45,078: initial_forget_bias: 3
2024-09-18 21:10:45,079: learning_rate: {0: 0.001, 5: 0.0005}
2024-09-18 21:10:45,079: log_interval: 5
2024-09-18 21:10:45,080: log_n_figures: 1
2024-09-18 21:10:45,080: log_tensorboard: True
2024-09-18 21:10:45,080: loss: NSE
2024-09-18 21:10:45,081: metrics: ['NSE', 'KGE', 'MSE']
2024-09-18 21:10:45,081: model: cudalstm
2024-09-18 21:10:45,082: num_workers: 16
2024-09-18 21:10:45,082: number_of_basins: 1
2024-09-18 21:10:45,082: optimizer: Adam
2024-09-18 21:10:45,083: output_activation: linear
2024-09-18 21:10:45,083: output_dropout: 0.4
2024-09-18 21:10:45,083: package_version: 1.11.0
2024-09-18 21:10:45,084: predict_last_n: 1
2024-09-18 21:10:45,084: regularization: None
2024-09-18 21:10:45,085: run_dir: /home/admin/Fine-Flood-Forecasts/experiment/finetuning_playground/runs/basin_09484600
2024-09-18 21:10:45,085: save_weights_every: 1
2024-09-18 21:10:45,086: seed: 721924
2024-09-18 21:10:45,086: seq_length: 365
2024-09-18 21:10:45,086: static_attributes: ['elev_mean', 'slope_mean', 'area_gages2', 'frac_forest', 'lai_max', 'lai_diff', 'gvf_max', 'gvf_diff', 'soil_depth_pelletier', 'soil_depth_statsgo', 'soil_porosity', 'soil_conductivity', 'max_water_content', 'sand_frac', 'silt_frac', 'clay_frac', 'carbonate_rocks_frac', 'geol_permeability', 'p_mean', 'pet_mean', 'aridity', 'frac_snow', 'high_prec_freq', 'high_prec_dur', 'low_prec_freq', 'low_prec_dur']
2024-09-18 21:10:45,087: target_noise_std: None
2024-09-18 21:10:45,087: target_variables: ['QObs(mm/d)']
2024-09-18 21:10:45,088: test_basin_file: finetune_basin.txt
2024-09-18 21:10:45,088: test_end_date: 1999-09-30 00:00:00
2024-09-18 21:10:45,088: test_start_date: 1989-10-01 00:00:00
2024-09-18 21:10:45,089: train_basin_file: finetune_basin.txt
2024-09-18 21:10:45,089: train_dir: /home/admin/Fine-Flood-Forecasts/experiment/finetuning_playground/runs/basin_09484600/train_data
2024-09-18 21:10:45,089: train_end_date: 2008-09-30 00:00:00
2024-09-18 21:10:45,090: train_start_date: 1999-10-01 00:00:00
2024-09-18 21:10:45,090: use_basin_id_encoding: False
2024-09-18 21:10:45,091: validate_every: 3
2024-09-18 21:10:45,091: validate_n_random_basins: 10
2024-09-18 21:10:45,092: validation_basin_file: finetune_basin.txt
2024-09-18 21:10:45,092: validation_end_date: 1989-09-30 00:00:00
2024-09-18 21:10:45,092: validation_start_date: 1980-10-01 00:00:00
2024-09-18 21:10:45,093: base_run_dir: /home/admin/Fine-Flood-Forecasts/experiment/models/runs/sota_20
2024-09-18 21:10:45,093: finetune_modules: ['lstm', 'head']
2024-09-18 21:10:45,093: is_finetuning: True
2024-09-18 21:10:45,094: is_continue_training: False
2024-09-18 21:10:45,095: ### Device cuda:0 will be used for training
2024-09-18 21:10:45,125: Loading basin data into xarray data set.
100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
2024-09-18 21:10:45,211: Calculating target variable stds per basin
100%|██████████| 1/1 [00:00<00:00, 832.86it/s]
2024-09-18 21:10:45,217: Create lookup table and convert to pytorch tensor
100%|██████████| 1/1 [00:00<00:00, 25.29it/s]
2024-09-18 21:10:45,288: Starting training from checkpoint /home/admin/Fine-Flood-Forecasts/experiment/models/runs/sota_20/model_epoch030.pt

/home/admin/Fine-Flood-Forecasts/neuralhydrology/training/basetrainer.py:160: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.model.load_state_dict(torch.load(str(checkpoint_path), map_location=self.device))

# Epoch 1: 100%|██████████| 13/13 [00:00<00:00, 21.24it/s, Loss: 0.0078]
2024-09-18 21:10:45,929: Epoch 1 average loss: avg_loss: 0.01099, avg_total_loss: 0.01099
# Epoch 2: 100%|██████████| 13/13 [00:00<00:00, 21.23it/s, Loss: 0.0043]
2024-09-18 21:10:46,551: Epoch 2 average loss: avg_loss: 0.00857, avg_total_loss: 0.00857
# Epoch 3: 100%|██████████| 13/13 [00:00<00:00, 20.85it/s, Loss: 0.0046]
2024-09-18 21:10:47,184: Epoch 3 average loss: avg_loss: 0.00833, avg_total_loss: 0.00833
# Validation:   0%|          | 0/1 [00:00<?, ?it/s]2024-09-18 21:10:47,306: The following basins had not enough valid target values to calculate a standard deviation: 09484600. NSE loss values for this basin will be NaN.
# Validation: 100%|██████████| 1/1 [00:00<00:00,  1.41it/s]
2024-09-18 21:10:48,090: Epoch 3 average validation loss: nan -- Median validation metrics: avg_loss: nan
# Epoch 4: 100%|██████████| 13/13 [00:00<00:00, 18.27it/s, Loss: 0.0106]
2024-09-18 21:10:48,804: Epoch 4 average loss: avg_loss: 0.00856, avg_total_loss: 0.00856
2024-09-18 21:10:48,811: Setting learning rate to 0.0005
# Epoch 5: 100%|██████████| 13/13 [00:00<00:00, 20.86it/s, Loss: 0.0050]
2024-09-18 21:10:49,438: Epoch 5 average loss: avg_loss: 0.00749, avg_total_loss: 0.00749
# Epoch 6: 100%|██████████| 13/13 [00:00<00:00, 19.82it/s, Loss: 0.0157]
2024-09-18 21:10:50,103: Epoch 6 average loss: avg_loss: 0.00776, avg_total_loss: 0.00776
# Validation: 100%|██████████| 1/1 [00:00<00:00,  1.69it/s]
2024-09-18 21:10:50,901: Epoch 6 average validation loss: nan -- Median validation metrics: avg_loss: nan
# Epoch 7: 100%|██████████| 13/13 [00:00<00:00, 20.06it/s, Loss: 0.0118]
2024-09-18 21:10:51,553: Epoch 7 average loss: avg_loss: 0.00702, avg_total_loss: 0.00702
# Epoch 8: 100%|██████████| 13/13 [00:00<00:00, 20.61it/s, Loss: 0.0099]
2024-09-18 21:10:52,193: Epoch 8 average loss: avg_loss: 0.00760, avg_total_loss: 0.00760
# Epoch 9: 100%|██████████| 13/13 [00:00<00:00, 20.66it/s, Loss: 0.0180]
2024-09-18 21:10:52,832: Epoch 9 average loss: avg_loss: 0.00726, avg_total_loss: 0.00726
# Validation: 100%|██████████| 1/1 [00:00<00:00,  1.69it/s]
2024-09-18 21:10:53,623: Epoch 9 average validation loss: nan -- Median validation metrics: avg_loss: nan
# Epoch 10: 100%|██████████| 13/13 [00:00<00:00, 20.04it/s, Loss: 0.0014]
2024-09-18 21:10:54,276: Epoch 10 average loss: avg_loss: 0.00721, avg_total_loss: 0.00721

In [58]:
run_dir = Path(os.path.abspath('')) / 'runs' / f'basin_{basin}'
config_file_path = run_dir / 'config.yml'
output_log = run_dir / 'output.log'

# plot the training and validation loss
train, val = get_losses(output_log)
train_epoch, train_ls = zip(*train.items()) 
val_epoch, val_ls = zip(*val.items()) 

plt.plot(train_epoch, train_ls)
plt.plot(val_epoch, val_ls)

ValueError: not enough values to unpack (expected 2, got 0)

In [59]:

finetuned_model = TrainedModel(config_file_path_or_experiment_name=config_file_path)
evaluate_models([model, finetuned_model], basins=[basin], include_benchmark=False, period='train')
evaluate_models([model, finetuned_model], basins=[basin], include_benchmark=False, period='test')

2024-09-18 21:11:01,870: Using the model weights from /home/admin/Fine-Flood-Forecasts/experiment/finetuning_playground/runs/basin_09484600/model_epoch010.pt

/home/admin/Fine-Flood-Forecasts/neuralhydrology/evaluation/tester.py:133: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.model.load_state_dict(torch.load(weight_file, map_location=self.device))

# Evaluation: 100%|██████████| 1/1 [00:00<00:00,  3.71it/s]
2024-09-18 21:11:02,145: Stored metrics at /home/admin/Fine-Flood-Forecasts/experiment/finetuning_playground/runs/basin_09484600/train/model_epoch010/train_metrics.csv
2024-09-18 21:11:02,146: Stored results at /home/admin/Fine-Flood-Forecasts/experiment/finetuning_playground/runs/basin_09484600/train/model_epoch010/train_results.p

2024-09-18 21:11:02,173: Using the model weights from /home/admin/Fine-Flood-Forecasts/experiment/finetuning_playground/runs/basin_09484600/model_epoch010.pt

/home/admin/Fine-Flood-Forecasts/neuralhydrology/evaluation/tester.py:133: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.model.load_state_dict(torch.load(weight_file, map_location=self.device))

# Evaluation:   0%|          | 0/1 [00:00<?, ?it/s]

# Evaluation: 100%|██████████| 1/1 [00:00<00:00,  3.58it/s]
2024-09-18 21:11:02,458: Stored metrics at /home/admin/Fine-Flood-Forecasts/experiment/finetuning_playground/runs/basin_09484600/test/model_epoch010/test_metrics.csv
2024-09-18 21:11:02,459: Stored results at /home/admin/Fine-Flood-Forecasts/experiment/finetuning_playground/runs/basin_09484600/test/model_epoch010/test_results.p

         Metric  sota_20 basin_09484600
0    NSE (mean)    -0.07    <b>0.01</b>
1    KGE (mean)     0.35    <b>0.54</b>
2    MSE (mean)     0.00     <b>0.0</b>
3  NSE (median)    -0.07    <b>0.01</b>
4  KGE (median)     0.35    <b>0.54</b>
5  MSE (median)     0.00     <b>0.0</b>